#ifndef GAPI_FUNCTIONS_HPP
#define GAPI_FUNCTIONS_HPP 1

#ifdef GAPI_FUNCTIONS_COMPILATION
#define FUNC(sig, name) gl_function<sig> name{noinit, #name}
#else
#define FUNC(sig, name) extern gl_function<sig> name
#endif // GAPI_FUNCTIONS_COMPILATION

namespace gapi{
	FUNC(void(GLuint, GLuint), glActiveShaderProgram);
	FUNC(void(GLenum), glActiveTexture);
	FUNC(void(GLuint, GLuint), glAttachShader);
	FUNC(void(GLuint, GLenum), glBeginConditionalRender);
	FUNC(void(GLenum, GLuint), glBeginQuery);
	FUNC(void(GLenum, GLuint, GLuint), glBeginQueryIndexed);
	FUNC(void(GLenum), glBeginTransformFeedback);
	FUNC(void(GLuint, GLuint, GLchar *), glBindAttribLocation);
	FUNC(void(GLenum, GLuint), glBindBuffer);
	FUNC(void(GLenum, GLuint, GLuint), glBindBufferBase);
	FUNC(void(GLenum, GLuint, GLuint, GLintptr, GLsizeiptr), glBindBufferRange);
	FUNC(void(GLuint, GLuint, char *), glBindFragDataLocation);
	FUNC(void(GLuint, GLuint, GLuint, char *), glBindFragDataLocationIndexed);
	FUNC(void(GLenum, GLuint), glBindFramebuffer);
	FUNC(void(GLuint), glBindProgramPipeline);
	FUNC(void(GLenum, GLuint), glBindRenderbuffer);
	FUNC(void(GLuint, GLuint), glBindSampler);
	FUNC(void(GLenum, GLuint), glBindTexture);
	FUNC(void(GLenum, GLuint), glBindTransformFeedback);
	FUNC(void(GLuint), glBindVertexArray);
	FUNC(void(GLclampf, GLclampf, GLclampf, GLclampf), glBlendColor);
	FUNC(void(GLenum), glBlendEquation);
	FUNC(void(GLenum, GLenum), glBlendEquationSeparate);
	FUNC(void(GLenum, GLenum), glBlendFunc);
	FUNC(void(GLenum, GLenum, GLenum, GLenum), glBlendFuncSeparate);
	FUNC(void(GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum), glBlitFramebuffer);
	FUNC(void(GLenum, GLsizeiptr, GLvoid *, GLenum), glBufferData);
	FUNC(void(GLenum, GLintptr, GLsizeiptr, GLvoid *), glBufferSubData);
	FUNC(GLenum(GLenum), glCheckFramebufferStatus);
	FUNC(void(GLenum, GLenum), glClampColor);
	FUNC(void(GLbitfield), glClear);
	FUNC(void(GLenum, GLint, GLint *), glClearBufferiv);
	FUNC(void(GLclampf, GLclampf, GLclampf, GLclampf), glClearColor);
	FUNC(void(GLclampd), glClearDepth);
	FUNC(void(GLint), glClearStencil);
	FUNC(GLenum(GLsync, GLbitfield, GLuint64), glClientWaitSync);
	FUNC(void(GLboolean, GLboolean, GLboolean, GLboolean), glColorMask);
	FUNC(void(GLuint), glCompileShader);
	FUNC(void(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, GLvoid *), glCompressedTexImage1D);
	FUNC(void(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, GLvoid *), glCompressedTexImage2D);
	FUNC(void(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, GLvoid *), glCompressedTexImage3D);
	FUNC(void(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, GLvoid *), glCompressedTexSubImage1D);
	FUNC(void(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, GLvoid *), glCompressedTexSubImage2D);
	FUNC(void(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, GLvoid *), glCompressedTexSubImage3D);
	FUNC(void(GLenum, GLenum, GLintptr, GLintptr, GLsizeiptr), glCopyBufferSubData);
	FUNC(void(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint), glCopyTexImage1D);
	FUNC(void(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint), glCopyTexImage2D);
	FUNC(void(GLenum, GLint, GLint, GLint, GLint, GLsizei), glCopyTexSubImage1D);
	FUNC(void(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei), glCopyTexSubImage2D);
	FUNC(void(GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei), glCopyTexSubImage3D);
	FUNC(GLuint(), glCreateProgram);
	FUNC(GLuint(GLenum), glCreateShader);
	FUNC(GLuint(GLenum, GLsizei, char **), glCreateShaderProgramv);
	FUNC(void(GLenum), glCullFace);
	FUNC(void(GLsizei, GLuint *), glDeleteBuffers);
	FUNC(void(GLsizei, GLuint *), glDeleteFramebuffers);
	FUNC(void(GLuint), glDeleteProgram);
	FUNC(void(GLsizei, GLuint *), glDeleteProgramPipelines);
	FUNC(void(GLsizei, GLuint *), glDeleteQueries);
	FUNC(void(GLsizei, GLuint *), glDeleteRenderbuffers);
	FUNC(void(GLsizei, GLuint *), glDeleteSamplers);
	FUNC(void(GLuint), glDeleteShader);
	FUNC(void(GLsync), glDeleteSync);
	FUNC(void(GLsizei, GLuint *), glDeleteTextures);
	FUNC(void(GLsizei, GLuint *), glDeleteTransformFeedbacks);
	FUNC(void(GLsizei, GLuint *), glDeleteVertexArrays);
	FUNC(void(GLenum), glDepthFunc);
	FUNC(void(GLboolean), glDepthMask);
	FUNC(void(GLclampd, GLclampd), glDepthRange);
	FUNC(void(GLuint, GLsizei, GLclampd *), glDepthRangeArrayv);
	FUNC(void(GLuint, GLclampd, GLclampd), glDepthRangeArrayv);
	FUNC(void(GLuint, GLuint), glDetachShader);
	FUNC(void(GLenum, GLint, GLsizei), glDrawArrays);
	FUNC(void(GLenum, void *), glDrawArraysIndirect);
	FUNC(void(GLenum, GLint, GLsizei, GLsizei), glDrawArraysInstanced);
	FUNC(void(GLenum), glDrawBuffer);
	FUNC(void(GLsizei, GLenum *), glDrawBuffers);
	FUNC(void(GLenum, GLsizei, GLenum, GLvoid *), glDrawElements);
	FUNC(void(GLenum, GLsizei, GLenum, GLvoid *, GLint), glDrawElementsBaseVertex);
	FUNC(void(GLenum, GLenum, void *), glDrawElementsIndirect);
	FUNC(void(GLenum, GLsizei, GLenum, void *, GLsizei), glDrawElementsInstanced);
	FUNC(void(GLenum, GLsizei, GLenum, GLvoid *, GLsizei, GLint), glDrawElementsInstancedBaseVertex);
	FUNC(void(GLenum, GLuint, GLuint, GLsizei, GLenum, GLvoid *), glDrawRangeElements);
	FUNC(void(GLenum, GLuint, GLuint, GLsizei, GLenum, GLvoid *, GLint), glDrawRangeElementsBaseVertex);
	FUNC(void(GLenum, GLuint), glDrawTransformFeedback);
	FUNC(void(GLenum, GLuint, GLuint), glDrawTransformFeedbackStream);
	FUNC(void(GLenum), glEnable);
	FUNC(void(GLuint), glEnableVertexAttribArray);
	FUNC(GLsync(GLenum, GLbitfield), glFenceSync);
	FUNC(void(), glFinish);
	FUNC(void(), glFlush);
	FUNC(GLsync(GLenum, GLintptr, GLsizeiptr), glFlushMappedBufferRange);
	FUNC(GLsync(GLenum, GLenum, GLenum, GLuint), glFramebufferRenderbuffer);
	FUNC(void(GLenum, GLenum, GLuint, GLint), glFramebufferTexture);
	FUNC(void(GLenum, GLenum, GLuint, GLint, GLint), glFramebufferTextureLayer);
	FUNC(void(GLenum), glFrontFace);
	FUNC(void(GLsizei, GLuint *), glGenBuffers);
	FUNC(void(GLsizei, GLuint *), glGenFramebuffers);
	FUNC(void(GLsizei, GLuint *), glGenProgramPipelines);
	FUNC(void(GLsizei, GLuint *), glGenQueries);
	FUNC(void(GLsizei, GLuint *), glGenRenderbuffers);
	FUNC(void(GLsizei, GLuint *), glGenSamplers);
	FUNC(void(GLsizei, GLuint *), glGenTextures);
	FUNC(void(GLsizei, GLuint *), glGenTransformFeedbacks);
	FUNC(void(GLsizei, GLuint *), glGenVertexArrays);
	FUNC(void(GLenum), glGenerateMipmap);
	FUNC(void(GLenum, GLboolean *), glGetBooleanv);
	FUNC(void(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *), glGetActiveAttrib);
	FUNC(void(GLuint, GLenum, GLuint, GLsizei, GLsizei *, GLchar *), glGetActiveSubroutineName);
	FUNC(void(GLuint, GLenum, GLuint, GLenum, GLint *), glGetActiveSubroutineUniformiv);
	FUNC(void(GLuint, GLenum, GLuint, GLsizei, GLsizei *, GLchar *), glGetActiveSubroutineUniformName);
	FUNC(void(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *), glGetActiveUniform);
	FUNC(void(GLuint, GLuint, GLenum, GLint), glGetActiveUniformBlockiv);
	FUNC(void(GLuint, GLuint, GLsizei, GLsizei *, GLchar *), glGetActiveUniformBlockName);
	FUNC(void(GLuint, GLuint, GLsizei, GLsizei *, GLchar *), glGetActiveUniformName);
	FUNC(void(GLuint, GLsizei, GLuint *, GLenum, GLint *), glGetActiveUniformsiv);
	FUNC(void(GLuint, GLsizei, GLsizei *, GLuint *), glGetAttachedShaders);
	FUNC(GLint(GLuint, GLchar *), glGetAttribLocation);
	FUNC(void(GLenum, GLenum, GLint *), glGetBufferParameteriv);
	FUNC(void(GLenum, GLenum, GLvoid **), glGetBufferPointerv);
	FUNC(void(GLenum, GLintptr, GLsizeiptr, GLvoid *), glGetBufferSubData);
	FUNC(void(GLenum, GLint, GLvoid *), glGetCompressedTexImage);
	FUNC(GLenum(), glGetError);
	FUNC(GLint(GLuint, char *), glGetFragDataIndex);
	FUNC(GLint(GLuint, char *), glGetFragDataLocation);
	FUNC(void(GLenum, GLenum, GLenum, GLint *), glGetFramebufferAttachmentParameter);
	FUNC(void(GLenum, GLuint, GLfloat *), glGetMultisamplefv);
	FUNC(void(GLuint, GLenum, GLint *), glGetProgramiv);
	FUNC(void(GLuint, GLsizei, GLsizei *, GLenum *, void *), glGetProgramBinary);
	FUNC(void(GLuint, GLsizei, GLsizei *, GLchar *), glGetProgramInfoLog);
	FUNC(void(GLuint, GLenum, GLint *), glGetProgramPipelineiv);
	FUNC(void(GLuint, GLsizei, GLsizei *, GLchar *), glGetProgramPipelineInfoLog);
	FUNC(void(GLuint, GLenum, GLenum, GLint *), glGetProgramStageiv);
	FUNC(void(GLenum, GLuint, GLenum, GLint *), glGetQueryIndexediv);
	FUNC(void(GLuint, GLenum, GLint *), glGetQueryObjectiv);
	FUNC(void(GLenum, GLenum, GLint *), glGetQueryiv);
	FUNC(void(GLenum, GLenum, GLint *), glGetRenderbufferParameteriv);
	FUNC(void(GLuint, GLenum, GLfloat *), glGetSamplerParameterfv);
	FUNC(void(GLuint, GLenum, GLint *), glGetShaderiv);
	FUNC(void(GLuint, GLsizei, GLsizei *, GLchar *), glGetShaderInfoLog);
	FUNC(void(GLenum, GLenum, GLint *, GLint *), glGetShaderPrecisionFormat);
	FUNC(void(GLuint, GLsizei, GLsizei *, GLchar *), glGetShaderSource);
	FUNC(GLubyte*(GLenum), glGetString);
	FUNC(GLuint(GLuint, GLenum, GLchar *), glGetSubroutineIndex);
	FUNC(GLint(GLuint, GLenum, GLchar *), glGetSubroutineUniformLocation);
	FUNC(void(GLsync, GLenum, GLsizei, GLsizei *, GLint *), glGetSynciv);
	FUNC(void(GLenum, GLint, GLenum, GLenum, GLvoid *), glGetTexImage);
	FUNC(void(GLenum, GLint, GLenum, GLfloat *), glGetTexLevelParameterfv);
	FUNC(void(GLenum, GLenum, GLfloat *), glGetTexParameterfv);
	FUNC(void(GLuint, GLuint, GLsizei, GLsizei *, GLsizei, GLenum *, char *), glGetTransformFeedbackVarying);
	FUNC(void(GLuint, GLint, GLfloat *), glGetUniformfv);
	FUNC(GLuint(GLuint, GLchar *), glGetUniformBlockIndex);
	FUNC(GLuint(GLuint, GLsizei, GLchar **, GLuint *), glGetUniformIndices);
	FUNC(GLint(GLuint, GLchar *), glGetUniformLocation);
	FUNC(void(GLenum, GLint, GLuint *), glGetUniformSubroutineuiv);
	FUNC(void(GLuint, GLenum, GLdouble *), glGetVertexAttribdv);
	FUNC(void(GLuint, GLenum, GLvoid **), glGetVertexAttribPointerv);
	FUNC(void(GLenum, GLenum), glHint);
	FUNC(GLboolean(GLuint), glIsBuffer);
	FUNC(GLboolean(GLenum), glIsEnabled);
	FUNC(GLboolean(GLuint), glIsFramebuffer);
	FUNC(GLboolean(GLuint), glIsProgram);
	FUNC(GLboolean(GLuint), glIsProgramPipeline);
	FUNC(GLboolean(GLuint), glIsQuery);
	FUNC(GLboolean(GLuint), glIsRenderbuffer);
	FUNC(GLboolean(GLuint), glIsSampler);
	FUNC(GLboolean(GLuint), glIsShader);
	FUNC(GLboolean(GLsync), glIsSync);
	FUNC(GLboolean(GLuint), glIsTexture);
	FUNC(GLboolean(GLuint), glIsTransformFeedback);
	FUNC(GLboolean(GLuint), glIsVertexArray);
	FUNC(void(GLfloat), glLineWidth);
	FUNC(void(GLuint), glLinkProgram);
	FUNC(void(GLenum), glLogicOp);
	FUNC(void *(GLenum, GLenum), glMapBuffer);
	FUNC(void *(GLenum, GLintptr, GLsizeiptr, GLbitfield), glMapBufferRange);
	FUNC(void(GLclampf), glMinSampleShading);
	FUNC(void(GLenum, GLint *, GLsizei *, GLsizei), glMultiDrawArrays);
	FUNC(void(GLenum, GLsizei *, GLenum, GLvoid **, GLsizei), glMultiDrawElements);
	FUNC(void(GLenum, GLsizei *, GLenum, GLvoid **, GLsizei, GLint *), glMultiDrawElementsBaseVertex);
	FUNC(void(GLenum, GLint), glPatchParameteri);
	FUNC(void(), glPauseTransformFeedback);
	FUNC(void(GLenum, GLfloat), glPixelStoref);
	FUNC(void(GLenum, GLfloat), glPointParameterf);
	FUNC(void(GLfloat), glPointSize);
	FUNC(void(GLenum, GLenum), glPolygonMode);
	FUNC(void(GLfloat, GLfloat), glPolygonOffset);
	FUNC(void(GLuint), glPrimitiveRestartIndex);
	FUNC(void(GLuint, GLenum, void *, GLsizei), glProgramBinary);
	FUNC(void(GLuint, GLenum, GLint), glProgramParameteri);
	FUNC(void(GLuint, GLint, GLfloat), glProgramUniform1f);
	FUNC(void(GLenum), glProvokingVertex);
	FUNC(void(GLuint, GLenum), glQueryCounter);
	FUNC(void(GLenum), glReadBuffer);
	FUNC(void(GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *), glReadPixels);
	FUNC(void(), glReleaseShaderCompiler);
	FUNC(void(GLenum, GLenum, GLsizei, GLsizei), glRenderbufferStorage);
	FUNC(void(GLenum, GLsizei, GLenum, GLsizei, GLsizei), glRenderbufferStorageMultisample);
	FUNC(void(), glResumeTransformFeedback);
	FUNC(void(GLclampf, GLboolean), glSampleCoverage);
	FUNC(void(GLuint, GLbitfield), glSampleMaski);
	FUNC(void(GLuint, GLenum, GLfloat), glSamplerParameterf);
	FUNC(void(GLint, GLint, GLsizei, GLsizei), glScissor);
	FUNC(void(GLuint, GLsizei, GLint *), glScissorArrayv);
	FUNC(void(GLuint, GLint, GLint, GLsizei, GLsizei), glScissorIndexed);
	FUNC(void(GLsizei, GLuint *, GLenum, void *, GLsizei), glShaderBinary);
	FUNC(void(GLuint, GLsizei, GLchar **, GLint *), glShaderSource);
	FUNC(void(GLenum, GLint, GLuint), glStencilFunc);
	FUNC(void(GLenum, GLenum, GLint, GLuint), glStencilFuncSeparate);
	FUNC(void(GLuint), glStencilMask);
	FUNC(void(GLenum, GLuint), glStencilMaskSeparate);
	FUNC(void(GLenum, GLenum, GLenum), glStencilOp);
	FUNC(void(GLenum, GLenum, GLenum, GLenum), glStencilOpSeparate);
	FUNC(void(GLenum, GLenum, GLuint), glTexBuffer);
	FUNC(void(GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, GLvoid *), glTexImage1D);
	FUNC(void(GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid *), glTexImage2D);
	FUNC(void(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLboolean), glTexImage2DMultisample);
	FUNC(void(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid *), glTexImage3D);
	FUNC(void(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLsizei, GLboolean), glTexImage3DMultisample);
	FUNC(void(GLenum, GLenum, GLfloat), glTexParameterf);
	FUNC(void(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, GLvoid *), glTexSubImage1D);
	FUNC(void(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *), glTexSubImage2D);
	FUNC(void(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, GLvoid *), glTexSubImage3D);
	FUNC(void(GLuint, GLsizei, char **, GLenum), glTransformFeedbackVaryings);
	FUNC(void(GLint, GLfloat), glUniform1f);
	FUNC(void(GLuint, GLuint, GLuint), glUniformBlockBinding);
	FUNC(void(GLenum, GLsizei, GLuint *), glUniformSubroutinesuiv);
	FUNC(void(GLuint), glUseProgram);
	FUNC(void(GLuint, GLbitfield, GLuint), glUseProgramStages);
	FUNC(void(GLuint), glValidateProgram);
	FUNC(void(GLuint), glValidateProgramPipeline);
	FUNC(void(GLuint, GLfloat), glVertexAttrib1f);
	FUNC(void(GLuint, GLuint), glVertexAttribDivisor);
	FUNC(void(GLuint, GLint, GLenum, GLboolean, GLsizei, GLvoid *), glVertexAttribPointer);
	FUNC(void(GLint, GLint, GLsizei, GLsizei), glViewport);
	FUNC(void(GLuint, GLsizei, GLfloat *), glViewportArrayv);
	FUNC(void(GLuint, GLfloat, GLfloat, GLfloat, GLfloat), glViewportIndexedf);
	FUNC(void(GLsync, GLbitfield, GLuint64), glWaitSync);
}

#undef FUNC

#endif // GAPI_FUNCTIONS_HPP
