#ifndef GAPI_FUNCTIONS_HPP
#define GAPI_FUNCTIONS_HPP 1

namespace gapi{
	namespace functions{
		gl_function<void(GLuint, GLuint)> glActiveShaderProgram{deferred_init, "glActiveShaderProgram"};
		gl_function<void(GLenum)> glActiveTexture{deferred_init, "glActiveTexture"};
		gl_function<void(GLuint, GLuint)> glAttachShader{deferred_init, "glAttachShader"};
		gl_function<void(GLuint, GLenum)> glBeginConditionalRender{deferred_init, "glBeginConditionalRender"};
		gl_function<void(GLenum, GLuint)> glBeginQuery{deferred_init, "glBeginQuery"};
		gl_function<void(GLenum, GLuint, GLuint)> glBeginQueryIndexed{deferred_init, "glBeginQueryIndexed"};
		gl_function<void(GLenum)> glBeginTransformFeedback{deferred_init, "glBeginTransformFeedback"};
		gl_function<void(GLuint, GLuint, GLchar *)> glBindAttribLocation{deferred_init, "glBindAttribLocation"};
		gl_function<void(GLenum, GLuint)> glBindBuffer{deferred_init, "glBindBuffer"};
		gl_function<void(GLenum, GLuint, GLuint)> glBindBufferBase{deferred_init, "glBindBufferBase"};
		gl_function<void(GLenum, GLuint, GLuint, GLintptr, GLsizeiptr)> glBindBufferRange{deferred_init, "glBindBufferRange"};
		gl_function<void(GLuint, GLuint, char *)> glBindFragDataLocation{deferred_init, "glBindFragDataLocation"};
		gl_function<void(GLuint, GLuint, GLuint, char *)> glBindFragDataLocationIndexed{deferred_init, "glBindFragDataLocationIndexed"};
		gl_function<void(GLenum, GLuint)> glBindFramebuffer{deferred_init, "glBindFramebuffer"};
		gl_function<void(GLuint)> glBindProgramPipeline{deferred_init, "glBindProgramPipeline"};
		gl_function<void(GLenum, GLuint)> glBindRenderbuffer{deferred_init, "glBindRenderbuffer"};
		gl_function<void(GLuint, GLuint)> glBindSampler{deferred_init, "glBindSampler"};
		gl_function<void(GLenum, GLuint)> glBindTexture{deferred_init, "glBindTexture"};
		gl_function<void(GLenum, GLuint)> glBindTransformFeedback{deferred_init, "glBindTransformFeedback"};
		gl_function<void(GLuint)> glBindVertexArray{deferred_init, "glBindVertexArray"};
		gl_function<void(GLclampf, GLclampf, GLclampf, GLclampf)> glBlendColor{deferred_init, "glBlendColor"};
		gl_function<void(GLenum)> glBlendEquation{deferred_init, "glBlendEquation"};
		gl_function<void(GLenum, GLenum)> glBlendEquationSeparate{deferred_init, "glBlendEquationSeparate"};
		gl_function<void(GLenum, GLenum)> glBlendFunc{deferred_init, "glBlendFunc"};
		gl_function<void(GLenum, GLenum, GLenum, GLenum)> glBlendFuncSeparate{deferred_init, "glBlendFuncSeparate"};
		gl_function<void(GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum)> glBlitFramebuffer{deferred_init, "glBlitFramebuffer"};
		gl_function<void(GLenum, GLsizeiptr, GLvoid *, GLenum)> glBufferData{deferred_init, "glBufferData"};
		gl_function<void(GLenum, GLintptr, GLsizeiptr, GLvoid *)> glBufferSubData{deferred_init, "glBufferSubData"};
		gl_function<GLenum(GLenum)> glCheckFramebufferStatus{deferred_init, "glCheckFramebufferStatus"};
		gl_function<void(GLenum, GLenum)> glClampColor{deferred_init, "glClampColor"};
		gl_function<void(GLbitfield)> glClear{deferred_init, "glClear"};
		gl_function<void(GLenum, GLint, GLint *)> glClearBufferiv{deferred_init, "glClearBufferiv"};
		gl_function<void(GLclampf, GLclampf, GLclampf, GLclampf)> glClearColor{deferred_init, "glClearColor"};
		gl_function<void(GLclampd)> glClearDepth{deferred_init, "glClearDepth"};
		gl_function<void(GLint)> glClearStencil{deferred_init, "glClearStencil"};
		gl_function<GLenum(GLsync, GLbitfield, GLuint64)> glClientWaitSync{deferred_init, "glClientWaitSync"};
		gl_function<void(GLboolean, GLboolean, GLboolean, GLboolean)> glColorMask{deferred_init, "glColorMask"};
		gl_function<void(GLuint)> glCompileShader{deferred_init, "glCompileShader"};
		gl_function<void(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, GLvoid *)> glCompressedTexImage1D{deferred_init, "glCompressedTexImage1D"};
		gl_function<void(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, GLvoid *)> glCompressedTexImage2D{deferred_init, "glCompressedTexImage2D"};
		gl_function<void(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, GLvoid *)> glCompressedTexImage3D{deferred_init, "glCompressedTexImage3D"};
		gl_function<void(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, GLvoid *)> glCompressedTexSubImage1D{deferred_init, "glCompressedTexSubImage1D"};
		gl_function<void(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, GLvoid *)> glCompressedTexSubImage2D{deferred_init, "glCompressedTexSubImage2D"};
		gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, GLvoid *)> glCompressedTexSubImage3D{deferred_init, "glCompressedTexSubImage3D"};
		gl_function<void(GLenum, GLenum, GLintptr, GLintptr, GLsizeiptr)> glCopyBufferSubData{deferred_init, "glCopyBufferSubData"};
		gl_function<void(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint)> glCopyTexImage1D{deferred_init, "glCopyTexImage1D"};
		gl_function<void(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint)> glCopyTexImage2D{deferred_init, "glCopyTexImage2D"};
		gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLsizei)> glCopyTexSubImage1D{deferred_init, "glCopyTexSubImage1D"};
		gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei)> glCopyTexSubImage2D{deferred_init, "glCopyTexSubImage2D"};
		gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei)> glCopyTexSubImage3D{deferred_init, "glCopyTexSubImage3D"};
		gl_function<GLuint()> glCreateProgram{deferred_init, "glCreateProgram"};
		gl_function<GLuint(GLenum)> glCreateShader{deferred_init, "glCreateShader"};
		gl_function<GLuint(GLenum, GLsizei, char **)> glCreateShaderProgramv{deferred_init, "glCreateShaderProgramv"};
		gl_function<void(GLenum)> glCullFace{deferred_init, "glCullFace"};
		gl_function<void(GLsizei, GLuint *)> glDeleteBuffers{deferred_init, "glDeleteBuffers"};
		gl_function<void(GLsizei, GLuint *)> glDeleteFramebuffers{deferred_init, "glDeleteFramebuffers"};
		gl_function<void(GLuint)> glDeleteProgram{deferred_init, "glDeleteProgram"};
		gl_function<void(GLsizei, GLuint *)> glDeleteProgramPipelines{deferred_init, "glDeleteProgramPipelines"};
		gl_function<void(GLsizei, GLuint *)> glDeleteQueries{deferred_init, "glDeleteQueries"};
		gl_function<void(GLsizei, GLuint *)> glDeleteRenderbuffers{deferred_init, "glDeleteRenderbuffers"};
		gl_function<void(GLsizei, GLuint *)> glDeleteSamplers{deferred_init, "glDeleteSamplers"};
		gl_function<void(GLuint)> glDeleteShader{deferred_init, "glDeleteShader"};
		gl_function<void(GLsync)> glDeleteSync{deferred_init, "glDeleteSync"};
		gl_function<void(GLsizei, GLuint *)> glDeleteTextures{deferred_init, "glDeleteTextures"};
		gl_function<void(GLsizei, GLuint *)> glDeleteTransformFeedbacks{deferred_init, "glDeleteTransformFeedbacks"};
		gl_function<void(GLsizei, GLuint *)> glDeleteVertexArrays{deferred_init, "glDeleteVertexArrays"};
		gl_function<void(GLenum)> glDepthFunc{deferred_init, "glDepthFunc"};
		gl_function<void(GLboolean)> glDepthMask{deferred_init, "glDepthMask"};
		gl_function<void(GLclampd, GLclampd)> glDepthRange{deferred_init, "glDepthRange"};
		gl_function<void(GLuint, GLsizei, GLclampd *)> glDepthRangeArrayv{deferred_init, "glDepthRangeArrayv"};
		gl_function<void(GLuint, GLclampd, GLclampd)> glDepthRangeArrayv{deferred_init, "glDepthRangeArrayv"};
		gl_function<void(GLuint, GLuint)> glDetachShader{deferred_init, "glDetachShader"};
		gl_function<void(GLenum, GLint, GLsizei)> glDrawArrays{deferred_init, "glDrawArrays"};
		gl_function<void(GLenum, void *)> glDrawArraysIndirect{deferred_init, "glDrawArraysIndirect"};
		gl_function<void(GLenum, GLint, GLsizei, GLsizei)> glDrawArraysInstanced{deferred_init, "glDrawArraysInstanced"};
		gl_function<void(GLenum)> glDrawBuffer{deferred_init, "glDrawBuffer"};
		gl_function<void(GLsizei, GLenum *)> glDrawBuffers{deferred_init, "glDrawBuffers"};
		gl_function<void(GLenum, GLsizei, GLenum, GLvoid *)> glDrawElements{deferred_init, "glDrawElements"};
		gl_function<void(GLenum, GLsizei, GLenum, GLvoid *, GLint)> glDrawElementsBaseVertex{deferred_init, "glDrawElementsBaseVertex"};
		gl_function<void(GLenum, GLenum, void *)> glDrawElementsIndirect{deferred_init, "glDrawElementsIndirect"};
		gl_function<void(GLenum, GLsizei, GLenum, void *, GLsizei)> glDrawElementsInstanced{deferred_init, "glDrawElementsInstanced"};
		gl_function<void(GLenum, GLsizei, GLenum, GLvoid *, GLsizei, GLint)> glDrawElementsInstancedBaseVertex{deferred_init, "glDrawElementsInstancedBaseVertex"};
		gl_function<void(GLenum, GLuint, GLuint, GLsizei, GLenum, GLvoid *)> glDrawRangeElements{deferred_init, "glDrawRangeElements"};
		gl_function<void(GLenum, GLuint, GLuint, GLsizei, GLenum, GLvoid *, GLint)> glDrawRangeElementsBaseVertex{deferred_init, "glDrawRangeElementsBaseVertex"};
		gl_function<void(GLenum, GLuint)> glDrawTransformFeedback{deferred_init, "glDrawTransformFeedback"};
		gl_function<void(GLenum, GLuint, GLuint)> glDrawTransformFeedbackStream{deferred_init, "glDrawTransformFeedbackStream"};
		gl_function<void(GLenum)> glEnable{deferred_init, "glEnable"};
		gl_function<void(GLuint)> glEnableVertexAttribArray{deferred_init, "glEnableVertexAttribArray"};
		gl_function<GLsync(GLenum, GLbitfield)> glFenceSync{deferred_init, "glFenceSync"};
		gl_function<void()> glFinish{deferred_init, "glFinish"};
		gl_function<void()> glFlush{deferred_init, "glFlush"};
		gl_function<GLsync(GLenum, GLintptr, GLsizeiptr)> glFlushMappedBufferRange{deferred_init, "glFlushMappedBufferRange"};
		gl_function<GLsync(GLenum, GLenum, GLenum, GLuint)> glFramebufferRenderbuffer{deferred_init, "glFramebufferRenderbuffer"};
		gl_function<void(GLenum, GLenum, GLuint, GLint)> glFramebufferTexture{deferred_init, "glFramebufferTexture"};
		gl_function<void(GLenum, GLenum, GLuint, GLint, GLint)> glFramebufferTextureLayer{deferred_init, "glFramebufferTextureLayer"};
		gl_function<void(GLenum)> glFrontFace{deferred_init, "glFrontFace"};
		gl_function<void(GLsizei, GLuint *)> glGenBuffers{deferred_init, "glGenBuffers"};
		gl_function<void(GLsizei, GLuint *)> glGenFramebuffers{deferred_init, "glGenFramebuffers"};
		gl_function<void(GLsizei, GLuint *)> glGenProgramPipelines{deferred_init, "glGenProgramPipelines"};
		gl_function<void(GLsizei, GLuint *)> glGenQueries{deferred_init, "glGenQueries"};
		gl_function<void(GLsizei, GLuint *)> glGenRenderbuffers{deferred_init, "glGenRenderbuffers"};
		gl_function<void(GLsizei, GLuint *)> glGenSamplers{deferred_init, "glGenSamplers"};
		gl_function<void(GLsizei, GLuint *)> glGenTextures{deferred_init, "glGenTextures"};
		gl_function<void(GLsizei, GLuint *)> glGenTransformFeedbacks{deferred_init, "glGenTransformFeedbacks"};
		gl_function<void(GLsizei, GLuint *)> glGenVertexArrays{deferred_init, "glGenVertexArrays"};
		gl_function<void(GLenum)> glGenerateMipmap{deferred_init, "glGenerateMipmap"};
		gl_function<void(GLenum, GLboolean *)> glGetBooleanv{deferred_init, "glGetBooleanv"};
		gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *)> glGetActiveAttrib{deferred_init, "glGetActiveAttrib"};
		gl_function<void(GLuint, GLenum, GLuint, GLsizei, GLsizei *, GLchar *)> glGetActiveSubroutineName{deferred_init, "glGetActiveSubroutineName"};
		gl_function<void(GLuint, GLenum, GLuint, GLenum, GLint *)> glGetActiveSubroutineUniformiv{deferred_init, "glGetActiveSubroutineUniformiv"};
		gl_function<void(GLuint, GLenum, GLuint, GLsizei, GLsizei *, GLchar *)> glGetActiveSubroutineUniformName{deferred_init, "glGetActiveSubroutineUniformName"};
		gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *)> glGetActiveUniform{deferred_init, "glGetActiveUniform"};
		gl_function<void(GLuint, GLuint, GLenum, GLint)> glGetActiveUniformBlockiv{deferred_init, "glGetActiveUniformBlockiv"};
		gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLchar *)> glGetActiveUniformBlockName{deferred_init, "glGetActiveUniformBlockName"};
		gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLchar *)> glGetActiveUniformName{deferred_init, "glGetActiveUniformName"};
		gl_function<void(GLuint, GLsizei, GLuint *, GLenum, GLint *)> glGetActiveUniformsiv{deferred_init, "glGetActiveUniformsiv"};
		gl_function<void(GLuint, GLsizei, GLsizei *, GLuint *)> glGetAttachedShaders{deferred_init, "glGetAttachedShaders"};
		gl_function<GLint(GLuint, GLchar *)> glGetAttribLocation{deferred_init, "glGetAttribLocation"};
		gl_function<void(GLenum, GLenum, GLint *)> glGetBufferParameteriv{deferred_init, "glGetBufferParameteriv"};
		gl_function<void(GLenum, GLenum, GLvoid **)> glGetBufferPointerv{deferred_init, "glGetBufferPointerv"};
		gl_function<void(GLenum, GLintptr, GLsizeiptr, GLvoid *)> glGetBufferSubData{deferred_init, "glGetBufferSubData"};
		gl_function<void(GLenum, GLint, GLvoid *)> glGetCompressedTexImage{deferred_init, "glGetCompressedTexImage"};
		gl_function<GLenum()> glGetError{deferred_init, "glGetError"};
		gl_function<GLint(GLuint, char *)> glGetFragDataIndex{deferred_init, "glGetFragDataIndex"};
		gl_function<GLint(GLuint, char *)> glGetFragDataLocation{deferred_init, "glGetFragDataLocation"};
		gl_function<void(GLenum, GLenum, GLenum, GLint *)> glGetFramebufferAttachmentParameter{deferred_init, "glGetFramebufferAttachmentParameter"};
		gl_function<void(GLenum, GLuint, GLfloat *)> glGetMultisamplefv{deferred_init, "glGetMultisamplefv"};
		gl_function<void(GLuint, GLenum, GLint *)> glGetProgramiv{deferred_init, "glGetProgramiv"};
		gl_function<void(GLuint, GLsizei, GLsizei *, GLenum *, void *)> glGetProgramBinary{deferred_init, "glGetProgramBinary"};
		gl_function<void(GLuint, GLsizei, GLsizei *, GLchar *)> glGetProgramInfoLog{deferred_init, "glGetProgramInfoLog"};
		gl_function<void(GLuint, GLenum, GLint *)> glGetProgramPipelineiv{deferred_init, "glGetProgramPipelineiv"};
		gl_function<void(GLuint, GLsizei, GLsizei *, GLchar *)> glGetProgramPipelineInfoLog{deferred_init, "glGetProgramPipelineInfoLog"};
		gl_function<void(GLuint, GLenum, GLenum, GLint *)> glGetProgramStageiv{deferred_init, "glGetProgramStageiv"};
		gl_function<void(GLenum, GLuint, GLenum, GLint *)> glGetQueryIndexediv{deferred_init, "glGetQueryIndexediv"};
		gl_function<void(GLuint, GLenum, GLint *)> glGetQueryObjectiv{deferred_init, "glGetQueryObjectiv"};
		gl_function<void(GLenum, GLenum, GLint *)> glGetQueryiv{deferred_init, "glGetQueryiv"};
		gl_function<void(GLenum, GLenum, GLint *)> glGetRenderbufferParameteriv{deferred_init, "glGetRenderbufferParameteriv"};
		gl_function<void(GLuint, GLenum, GLfloat *)> glGetSamplerParameterfv{deferred_init, "glGetSamplerParameterfv"};
		gl_function<void(GLuint, GLenum, GLint *)> glGetShaderiv{deferred_init, "glGetShaderiv"};
		gl_function<void(GLuint, GLsizei, GLsizei *, GLchar *)> glGetShaderInfoLog{deferred_init, "glGetShaderInfoLog"};
		gl_function<void(GLenum, GLenum, GLint *, GLint *)> glGetShaderPrecisionFormat{deferred_init, "glGetShaderPrecisionFormat"};
		gl_function<void(GLuint, GLsizei, GLsizei *, GLchar *)> glGetShaderSource{deferred_init, "glGetShaderSource"};
		gl_function<GLubyte*(GLenum)> glGetString{deferred_init, "glGetString"};
		gl_function<GLuint(GLuint, GLenum, GLchar *)> glGetSubroutineIndex{deferred_init, "glGetSubroutineIndex"};
		gl_function<GLint(GLuint, GLenum, GLchar *)> glGetSubroutineUniformLocation{deferred_init, "glGetSubroutineUniformLocation"};
		gl_function<void(GLsync, GLenum, GLsizei, GLsizei *, GLint *)> glGetSynciv{deferred_init, "glGetSynciv"};
		gl_function<void(GLenum, GLint, GLenum, GLenum, GLvoid *)> glGetTexImage{deferred_init, "glGetTexImage"};
		gl_function<void(GLenum, GLint, GLenum, GLfloat *)> glGetTexLevelParameterfv{deferred_init, "glGetTexLevelParameterfv"};
		gl_function<void(GLenum, GLenum, GLfloat *)> glGetTexParameterfv{deferred_init, "glGetTexParameterfv"};
		gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLsizei, GLenum *, char *)> glGetTransformFeedbackVarying{deferred_init, "glGetTransformFeedbackVarying"};
		gl_function<void(GLuint, GLint, GLfloat *)> glGetUniformfv{deferred_init, "glGetUniformfv"};
		gl_function<GLuint(GLuint, GLchar *)> glGetUniformBlockIndex{deferred_init, "glGetUniformBlockIndex"};
		gl_function<GLuint(GLuint, GLsizei, GLchar **, GLuint *)> glGetUniformIndices{deferred_init, "glGetUniformIndices"};
		gl_function<GLint(GLuint, GLchar *)> glGetUniformLocation{deferred_init, "glGetUniformLocation"};
		gl_function<void(GLenum, GLint, GLuint *)> glGetUniformSubroutineuiv{deferred_init, "glGetUniformSubroutineuiv"};
		gl_function<void(GLuint, GLenum, GLdouble *)> glGetVertexAttribdv{deferred_init, "glGetVertexAttribdv"};
		gl_function<void(GLuint, GLenum, GLvoid **)> glGetVertexAttribPointerv{deferred_init, "glGetVertexAttribPointerv"};
		gl_function<void(GLenum, GLenum)> glHint{deferred_init, "glHint"};
		gl_function<GLboolean(GLuint)> glIsBuffer{deferred_init, "glIsBuffer"};
		gl_function<GLboolean(GLenum)> glIsEnabled{deferred_init, "glIsEnabled"};
		gl_function<GLboolean(GLuint)> glIsFramebuffer{deferred_init, "glIsFramebuffer"};
		gl_function<GLboolean(GLuint)> glIsProgram{deferred_init, "glIsProgram"};
		gl_function<GLboolean(GLuint)> glIsProgramPipeline{deferred_init, "glIsProgramPipeline"};
		gl_function<GLboolean(GLuint)> glIsQuery{deferred_init, "glIsQuery"};
		gl_function<GLboolean(GLuint)> glIsRenderbuffer{deferred_init, "glIsRenderbuffer"};
		gl_function<GLboolean(GLuint)> glIsSampler{deferred_init, "glIsSampler"};
		gl_function<GLboolean(GLuint)> glIsShader{deferred_init, "glIsShader"};
		gl_function<GLboolean(GLsync)> glIsSync{deferred_init, "glIsSync"};
		gl_function<GLboolean(GLuint)> glIsTexture{deferred_init, "glIsTexture"};
		gl_function<GLboolean(GLuint)> glIsTransformFeedback{deferred_init, "glIsTransformFeedback"};
		gl_function<GLboolean(GLuint)> glIsVertexArray{deferred_init, "glIsVertexArray"};
		gl_function<void(GLfloat)> glLineWidth{deferred_init, "glLineWidth"};
		gl_function<void(GLuint)> glLinkProgram{deferred_init, "glLinkProgram"};
		gl_function<void(GLenum)> glLogicOp{deferred_init, "glLogicOp"};
		gl_function<void *(GLenum, GLenum)> glMapBuffer{deferred_init, "glMapBuffer"};
		gl_function<void *(GLenum, GLintptr, GLsizeiptr, GLbitfield)> glMapBufferRange{deferred_init, "glMapBufferRange"};
		gl_function<void(GLclampf)> glMinSampleShading{deferred_init, "glMinSampleShading"};
		gl_function<void(GLenum, GLint *, GLsizei *, GLsizei)> glMultiDrawArrays{deferred_init, "glMultiDrawArrays"};
		gl_function<void(GLenum, GLsizei *, GLenum, GLvoid **, GLsizei)> glMultiDrawElements{deferred_init, "glMultiDrawElements"};
		gl_function<void(GLenum, GLsizei *, GLenum, GLvoid **, GLsizei, GLint *)> glMultiDrawElementsBaseVertex{deferred_init, "glMultiDrawElementsBaseVertex"};
		gl_function<void(GLenum, GLint)> glPatchParameteri{deferred_init, "glPatchParameteri"};
		gl_function<void()> glPauseTransformFeedback{deferred_init, "glPauseTransformFeedback"};
		gl_function<void(GLenum, GLfloat)> glPixelStoref{deferred_init, "glPixelStoref"};
		gl_function<void(GLenum, GLfloat)> glPointParameterf{deferred_init, "glPointParameterf"};
		gl_function<void(GLfloat)> glPointSize{deferred_init, "glPointSize"};
		gl_function<void(GLenum, GLenum)> glPolygonMode{deferred_init, "glPolygonMode"};
		gl_function<void(GLfloat, GLfloat)> glPolygonOffset{deferred_init, "glPolygonOffset"};
		gl_function<void(GLuint)> glPrimitiveRestartIndex{deferred_init, "glPrimitiveRestartIndex"};
		gl_function<void(GLuint, GLenum, void *, GLsizei)> glProgramBinary{deferred_init, "glProgramBinary"};
		gl_function<void(GLuint, GLenum, GLint)> glProgramParameteri{deferred_init, "glProgramParameteri"};
		gl_function<void(GLuint, GLint, GLfloat)> glProgramUniform1f{deferred_init, "glProgramUniform1f"};
		gl_function<void(GLenum)> glProvokingVertex{deferred_init, "glProvokingVertex"};
		gl_function<void(GLuint, GLenum)> glQueryCounter{deferred_init, "glQueryCounter"};
		gl_function<void(GLenum)> glReadBuffer{deferred_init, "glReadBuffer"};
		gl_function<void(GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *)> glReadPixels{deferred_init, "glReadPixels"};
		gl_function<void()> glReleaseShaderCompiler{deferred_init, "glReleaseShaderCompiler"};
		gl_function<void(GLenum, GLenum, GLsizei, GLsizei)> glRenderbufferStorage{deferred_init, "glRenderbufferStorage"};
		gl_function<void(GLenum, GLsizei, GLenum, GLsizei, GLsizei)> glRenderbufferStorageMultisample{deferred_init, "glRenderbufferStorageMultisample"};
		gl_function<void()> glResumeTransformFeedback{deferred_init, "glResumeTransformFeedback"};
		gl_function<void(GLclampf, GLboolean)> glSampleCoverage{deferred_init, "glSampleCoverage"};
		gl_function<void(GLuint, GLbitfield)> glSampleMaski{deferred_init, "glSampleMaski"};
		gl_function<void(GLuint, GLenum, GLfloat)> glSamplerParameterf{deferred_init, "glSamplerParameterf"};
		gl_function<void(GLint, GLint, GLsizei, GLsizei)> glScissor{deferred_init, "glScissor"};
		gl_function<void(GLuint, GLsizei, GLint *)> glScissorArrayv{deferred_init, "glScissorArrayv"};
		gl_function<void(GLuint, GLint, GLint, GLsizei, GLsizei)> glScissorIndexed{deferred_init, "glScissorIndexed"};
		gl_function<void(GLsizei, GLuint *, GLenum, void *, GLsizei)> glShaderBinary{deferred_init, "glShaderBinary"};
		gl_function<void(GLuint, GLsizei, GLchar **, GLint *)> glShaderSource{deferred_init, "glShaderSource"};
		gl_function<void(GLenum, GLint, GLuint)> glStencilFunc{deferred_init, "glStencilFunc"};
		gl_function<void(GLenum, GLenum, GLint, GLuint)> glStencilFuncSeparate{deferred_init, "glStencilFuncSeparate"};
		gl_function<void(GLuint)> glStencilMask{deferred_init, "glStencilMask"};
		gl_function<void(GLenum, GLuint)> glStencilMaskSeparate{deferred_init, "glStencilMaskSeparate"};
		gl_function<void(GLenum, GLenum, GLenum)> glStencilOp{deferred_init, "glStencilOp"};
		gl_function<void(GLenum, GLenum, GLenum, GLenum)> glStencilOpSeparate{deferred_init, "glStencilOpSeparate"};
		gl_function<void(GLenum, GLenum, GLuint)> glTexBuffer{deferred_init, "glTexBuffer"};
		gl_function<void(GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, GLvoid *)> glTexImage1D{deferred_init, "glTexImage1D"};
		gl_function<void(GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid *)> glTexImage2D{deferred_init, "glTexImage2D"};
		gl_function<void(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLboolean)> glTexImage2DMultisample{deferred_init, "glTexImage2DMultisample"};
		gl_function<void(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid *)> glTexImage3D{deferred_init, "glTexImage3D"};
		gl_function<void(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLsizei, GLboolean)> glTexImage3DMultisample{deferred_init, "glTexImage3DMultisample"};
		gl_function<void(GLenum, GLenum, GLfloat)> glTexParameterf{deferred_init, "glTexParameterf"};
		gl_function<void(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, GLvoid *)> glTexSubImage1D{deferred_init, "glTexSubImage1D"};
		gl_function<void(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *)> glTexSubImage2D{deferred_init, "glTexSubImage2D"};
		gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, GLvoid *)> glTexSubImage3D{deferred_init, "glTexSubImage3D"};
		gl_function<void(GLuint, GLsizei, char **, GLenum)> glTransformFeedbackVaryings{deferred_init, "glTransformFeedbackVaryings"};
		gl_function<void(GLint, GLfloat)> glUniform1f{deferred_init, "glUniform1f"};
		gl_function<void(GLuint, GLuint, GLuint)> glUniformBlockBinding{deferred_init, "glUniformBlockBinding"};
		gl_function<void(GLenum, GLsizei, GLuint *)> glUniformSubroutinesuiv{deferred_init, "glUniformSubroutinesuiv"};
		gl_function<void(GLuint)> glUseProgram{deferred_init, "glUseProgram"};
		gl_function<void(GLuint, GLbitfield, GLuint)> glUseProgramStages{deferred_init, "glUseProgramStages"};
		gl_function<void(GLuint)> glValidateProgram{deferred_init, "glValidateProgram"};
		gl_function<void(GLuint)> glValidateProgramPipeline{deferred_init, "glValidateProgramPipeline"};
		gl_function<void(GLuint, GLfloat)> glVertexAttrib1f{deferred_init, "glVertexAttrib1f"};
		gl_function<void(GLuint, GLuint)> glVertexAttribDivisor{deferred_init, "glVertexAttribDivisor"};
		gl_function<void(GLuint, GLint, GLenum, GLboolean, GLsizei, GLvoid *)> glVertexAttribPointer{deferred_init, "glVertexAttribPointer"};
		gl_function<void(GLint, GLint, GLsizei, GLsizei)> glViewport{deferred_init, "glViewport"};
		gl_function<void(GLuint, GLsizei, GLfloat *)> glViewportArrayv{deferred_init, "glViewportArrayv"};
		gl_function<void(GLuint, GLfloat, GLfloat, GLfloat, GLfloat)> glViewportIndexedf{deferred_init, "glViewportIndexedf"};
		gl_function<void(GLsync, GLbitfield, GLuint64)> glWaitSync{deferred_init, "glWaitSync"};
	}
}

#undef FUNC

#endif // GAPI_FUNCTIONS_HPP
