#ifndef GAPI_FUNCTIONS_HPP
#define GAPI_FUNCTIONS_HPP 1

#include "gapi.hpp"
#include "types.hpp"

namespace gapi{
	namespace functions{
		extern gl_function<void(GLuint, GLuint)> glActiveShaderProgram;
		extern gl_function<void(GLenum)> glActiveTexture;
		extern gl_function<void(GLuint, GLuint)> glAttachShader;
		extern gl_function<void(GLuint, GLenum)> glBeginConditionalRender;
		extern gl_function<void()> glEndConditionalRender;
		extern gl_function<void(GLenum, GLuint)> glBeginQuery;
		extern gl_function<void(GLenum)> glEndQuery;
		extern gl_function<void(GLenum, GLuint, GLuint)> glBeginQueryIndexed;
		extern gl_function<void(GLenum, GLuint)> glEndQueryIndexed;
		extern gl_function<void(GLenum)> glBeginTransformFeedback;
		extern gl_function<void()> glEndTransformFeedback;
		extern gl_function<void(GLuint, GLuint, GLchar *)> glBindAttribLocation;
		extern gl_function<void(GLenum, GLuint)> glBindBuffer;
		extern gl_function<void(GLenum, GLuint, GLuint)> glBindBufferBase;
		extern gl_function<void(GLenum, GLuint, GLuint, GLintptr, GLsizeiptr)> glBindBufferRange;
		extern gl_function<void(GLuint, GLuint, char *)> glBindFragDataLocation;
		extern gl_function<void(GLuint, GLuint, GLuint, char *)> glBindFragDataLocationIndexed;
		extern gl_function<void(GLenum, GLuint)> glBindFramebuffer;
		extern gl_function<void(GLuint)> glBindProgramPipeline;
		extern gl_function<void(GLenum, GLuint)> glBindRenderbuffer;
		extern gl_function<void(GLuint, GLuint)> glBindSampler;
		extern gl_function<void(GLenum, GLuint)> glBindTexture;
		extern gl_function<void(GLenum, GLuint)> glBindTransformFeedback;
		extern gl_function<void(GLuint)> glBindVertexArray;
		extern gl_function<void(GLclampf, GLclampf, GLclampf, GLclampf)> glBlendColor;
		extern gl_function<void(GLenum)> glBlendEquation;
		extern gl_function<void(GLuint, GLenum)> glBlendEquationi;
		extern gl_function<void(GLenum, GLenum)> glBlendEquationSeparate;
		extern gl_function<void(GLuint, GLenum, GLenum)> glBlendEquationSeparatei;
		extern gl_function<void(GLenum, GLenum)> glBlendFunc;
		extern gl_function<void(GLuint, GLenum, GLenum)> glBlendFunci;
		extern gl_function<void(GLenum, GLenum, GLenum, GLenum)> glBlendFuncSeparate;
		extern gl_function<void(GLuint, GLenum, GLenum, GLenum, GLenum)> glBlendFuncSeparatei;
		extern gl_function<void(GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum)> glBlitFramebuffer;
		extern gl_function<void(GLenum, GLsizeiptr, GLvoid *, GLenum)> glBufferData;
		extern gl_function<void(GLenum, GLintptr, GLsizeiptr, GLvoid *)> glBufferSubData;
		extern gl_function<GLenum(GLenum)> glCheckFramebufferStatus;
		extern gl_function<void(GLenum, GLenum)> glClampColor;
		extern gl_function<void(GLbitfield)> glClear;
		extern gl_function<void(GLenum, GLint, GLint *)> glClearBufferiv;
		extern gl_function<void(GLenum, GLint, GLuint *)> glClearBufferuiv;
		extern gl_function<void(GLenum, GLint, GLfloat *)> glClearBufferfv;
		extern gl_function<void(GLenum, GLint, GLfloat, GLint)> glClearBufferfi;
		extern gl_function<void(GLclampf, GLclampf, GLclampf, GLclampf)> glClearColor;
		extern gl_function<void(GLclampd)> glClearDepth;
		extern gl_function<void(GLclampf)> glClearDepthf;
		extern gl_function<void(GLint)> glClearStencil;
		extern gl_function<GLenum(GLsync, GLbitfield, GLuint64)> glClientWaitSync;
		extern gl_function<void(GLboolean, GLboolean, GLboolean, GLboolean)> glColorMask;
		extern gl_function<void(GLuint)> glCompileShader;
		extern gl_function<void(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, GLvoid *)> glCompressedTexImage1D;
		extern gl_function<void(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, GLvoid *)> glCompressedTexImage2D;
		extern gl_function<void(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, GLvoid *)> glCompressedTexImage3D;
		extern gl_function<void(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, GLvoid *)> glCompressedTexSubImage1D;
		extern gl_function<void(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, GLvoid *)> glCompressedTexSubImage2D;
		extern gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, GLvoid *)> glCompressedTexSubImage3D;
		extern gl_function<void(GLenum, GLenum, GLintptr, GLintptr, GLsizeiptr)> glCopyBufferSubData;
		extern gl_function<void(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint)> glCopyTexImage1D;
		extern gl_function<void(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint)> glCopyTexImage2D;
		extern gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLsizei)> glCopyTexSubImage1D;
		extern gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei)> glCopyTexSubImage2D;
		extern gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei)> glCopyTexSubImage3D;
		extern gl_function<GLuint()> glCreateProgram;
		extern gl_function<GLuint(GLenum)> glCreateShader;
		extern gl_function<GLuint(GLenum, GLsizei, char **)> glCreateShaderProgramv;
		extern gl_function<void(GLenum)> glCullFace;
		extern gl_function<void(GLsizei, GLuint *)> glDeleteBuffers;
		extern gl_function<void(GLsizei, GLuint *)> glDeleteFramebuffers;
		extern gl_function<void(GLuint)> glDeleteProgram;
		extern gl_function<void(GLsizei, GLuint *)> glDeleteProgramPipelines;
		extern gl_function<void(GLsizei, GLuint *)> glDeleteQueries;
		extern gl_function<void(GLsizei, GLuint *)> glDeleteRenderbuffers;
		extern gl_function<void(GLsizei, GLuint *)> glDeleteSamplers;
		extern gl_function<void(GLuint)> glDeleteShader;
		extern gl_function<void(GLsync)> glDeleteSync;
		extern gl_function<void(GLsizei, GLuint *)> glDeleteTextures;
		extern gl_function<void(GLsizei, GLuint *)> glDeleteTransformFeedbacks;
		extern gl_function<void(GLsizei, GLuint *)> glDeleteVertexArrays;
		extern gl_function<void(GLenum)> glDepthFunc;
		extern gl_function<void(GLboolean)> glDepthMask;
		extern gl_function<void(GLclampd, GLclampd)> glDepthRange;
		extern gl_function<void(GLclampf, GLclampf)> glDepthRangef;
		extern gl_function<void(GLuint, GLsizei, GLclampd *)> glDepthRangeArrayv;
		extern gl_function<void(GLuint, GLclampd, GLclampd)> glDepthRangeIndexed;
		extern gl_function<void(GLuint, GLuint)> glDetachShader;
		extern gl_function<void(GLenum, GLint, GLsizei)> glDrawArrays;
		extern gl_function<void(GLenum, void *)> glDrawArraysIndirect;
		extern gl_function<void(GLenum, GLint, GLsizei, GLsizei)> glDrawArraysInstanced;
		extern gl_function<void(GLenum)> glDrawBuffer;
		extern gl_function<void(GLsizei, GLenum *)> glDrawBuffers;
		extern gl_function<void(GLenum, GLsizei, GLenum, GLvoid *)> glDrawElements;
		extern gl_function<void(GLenum, GLsizei, GLenum, GLvoid *, GLint)> glDrawElementsBaseVertex;
		extern gl_function<void(GLenum, GLenum, void *)> glDrawElementsIndirect;
		extern gl_function<void(GLenum, GLsizei, GLenum, void *, GLsizei)> glDrawElementsInstanced;
		extern gl_function<void(GLenum, GLsizei, GLenum, GLvoid *, GLsizei, GLint)> glDrawElementsInstancedBaseVertex;
		extern gl_function<void(GLenum, GLuint, GLuint, GLsizei, GLenum, GLvoid *)> glDrawRangeElements;
		extern gl_function<void(GLenum, GLuint, GLuint, GLsizei, GLenum, GLvoid *, GLint)> glDrawRangeElementsBaseVertex;
		extern gl_function<void(GLenum, GLuint)> glDrawTransformFeedback;
		extern gl_function<void(GLenum, GLuint, GLuint)> glDrawTransformFeedbackStream;
		extern gl_function<void(GLenum)> glEnable;
		extern gl_function<void(GLenum)> glDisable;
		extern gl_function<void(GLenum, GLuint)> glEnablei;
		extern gl_function<void(GLenum, GLuint)> glDisablei;
		extern gl_function<void(GLuint)> glEnableVertexAttribArray;
		extern gl_function<void(GLuint)> glDisableVertexAttribArray;
		extern gl_function<GLsync(GLenum, GLbitfield)> glFenceSync;
		extern gl_function<void()> glFinish;
		extern gl_function<void()> glFlush;
		extern gl_function<GLsync(GLenum, GLintptr, GLsizeiptr)> glFlushMappedBufferRange;
		extern gl_function<GLsync(GLenum, GLenum, GLenum, GLuint)> glFramebufferRenderbuffer;
		extern gl_function<void(GLenum, GLenum, GLuint, GLint)> glFramebufferTexture;
		extern gl_function<void(GLenum, GLenum, GLenum, GLuint, GLint)> glFramebufferTexture1D;
		extern gl_function<void(GLenum, GLenum, GLenum, GLuint, GLint)> glFramebufferTexture2D;
		extern gl_function<void(GLenum, GLenum, GLenum, GLuint, GLint, GLint)> glFramebufferTexture3D;
		extern gl_function<void(GLenum, GLenum, GLuint, GLint, GLint)> glFramebufferTextureLayer;
		extern gl_function<void(GLenum)> glFrontFace;
		extern gl_function<void(GLsizei, GLuint *)> glGenBuffers;
		extern gl_function<void(GLsizei, GLuint *)> glGenFramebuffers;
		extern gl_function<void(GLsizei, GLuint *)> glGenProgramPipelines;
		extern gl_function<void(GLsizei, GLuint *)> glGenQueries;
		extern gl_function<void(GLsizei, GLuint *)> glGenRenderbuffers;
		extern gl_function<void(GLsizei, GLuint *)> glGenSamplers;
		extern gl_function<void(GLsizei, GLuint *)> glGenTextures;
		extern gl_function<void(GLsizei, GLuint *)> glGenTransformFeedbacks;
		extern gl_function<void(GLsizei, GLuint *)> glGenVertexArrays;
		extern gl_function<void(GLenum)> glGenerateMipmap;
		extern gl_function<void(GLenum, GLboolean *)> glGetBooleanv;
		extern gl_function<void(GLenum, GLdouble *)> glGetDoublev;
		extern gl_function<void(GLenum, GLfloat *)> glGetFloatv;
		extern gl_function<void(GLenum, GLint *)> glGetIntegerv;
		extern gl_function<void(GLenum, GLint64 *)> glGetInteger64v;
		extern gl_function<void(GLenum, GLuint, GLboolean *)> glGetBooleani_v;
		extern gl_function<void(GLenum, GLuint, GLint *)> glGetIntegeri_v;
		extern gl_function<void(GLenum, GLuint, GLint64 *)> glGetInteger64i_v;
		extern gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *)> glGetActiveAttrib;
		extern gl_function<void(GLuint, GLenum, GLuint, GLsizei, GLsizei *, GLchar *)> glGetActiveSubroutineName;
		extern gl_function<void(GLuint, GLenum, GLuint, GLenum, GLint *)> glGetActiveSubroutineUniformiv;
		extern gl_function<void(GLuint, GLenum, GLuint, GLsizei, GLsizei *, GLchar *)> glGetActiveSubroutineUniformName;
		extern gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLchar *)> glGetActiveUniform;
		extern gl_function<void(GLuint, GLuint, GLenum, GLint)> glGetActiveUniformBlockiv;
		extern gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLchar *)> glGetActiveUniformBlockName;
		extern gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLchar *)> glGetActiveUniformName;
		extern gl_function<void(GLuint, GLsizei, GLuint *, GLenum, GLint *)> glGetActiveUniformsiv;
		extern gl_function<void(GLuint, GLsizei, GLsizei *, GLuint *)> glGetAttachedShaders;
		extern gl_function<GLint(GLuint, GLchar *)> glGetAttribLocation;
		extern gl_function<void(GLenum, GLenum, GLint *)> glGetBufferParameteriv;
		extern gl_function<void(GLenum, GLenum, GLvoid **)> glGetBufferPointerv;
		extern gl_function<void(GLenum, GLintptr, GLsizeiptr, GLvoid *)> glGetBufferSubData;
		extern gl_function<void(GLenum, GLint, GLvoid *)> glGetCompressedTexImage;
		extern gl_function<GLenum()> glGetError;
		extern gl_function<GLint(GLuint, char *)> glGetFragDataIndex;
		extern gl_function<GLint(GLuint, char *)> glGetFragDataLocation;
		extern gl_function<void(GLenum, GLenum, GLenum, GLint *)> glGetFramebufferAttachmentParameter;
		extern gl_function<void(GLenum, GLuint, GLfloat *)> glGetMultisamplefv;
		extern gl_function<void(GLuint, GLenum, GLint *)> glGetProgramiv;
		extern gl_function<void(GLuint, GLsizei, GLsizei *, GLenum *, void *)> glGetProgramBinary;
		extern gl_function<void(GLuint, GLsizei, GLsizei *, GLchar *)> glGetProgramInfoLog;
		extern gl_function<void(GLuint, GLenum, GLint *)> glGetProgramPipelineiv;
		extern gl_function<void(GLuint, GLsizei, GLsizei *, GLchar *)> glGetProgramPipelineInfoLog;
		extern gl_function<void(GLuint, GLenum, GLenum, GLint *)> glGetProgramStageiv;
		extern gl_function<void(GLenum, GLuint, GLenum, GLint *)> glGetQueryIndexediv;
		extern gl_function<void(GLuint, GLenum, GLint *)> glGetQueryObjectiv;
		extern gl_function<void(GLuint, GLenum, GLuint *)> glGetQueryObjectuiv;
		extern gl_function<void(GLuint, GLenum, GLint64 *)> glGetQueryObjecti64v;
		extern gl_function<void(GLuint, GLenum, GLuint64 *)> glGetQueryObjectui64v;
		extern gl_function<void(GLenum, GLenum, GLint *)> glGetQueryiv;
		extern gl_function<void(GLenum, GLenum, GLint *)> glGetRenderbufferParameteriv;
		extern gl_function<void(GLuint, GLenum, GLfloat *)> glGetSamplerParameterfv;
		extern gl_function<void(GLuint, GLenum, GLint *)> glGetSamplerParameteriv;
		extern gl_function<void(GLuint, GLenum, GLint *)> glGetShaderiv;
		extern gl_function<void(GLuint, GLsizei, GLsizei *, GLchar *)> glGetShaderInfoLog;
		extern gl_function<void(GLenum, GLenum, GLint *, GLint *)> glGetShaderPrecisionFormat;
		extern gl_function<void(GLuint, GLsizei, GLsizei *, GLchar *)> glGetShaderSource;
		extern gl_function<GLubyte*(GLenum)> glGetString;
		extern gl_function<GLubyte*(GLenum, GLuint)> glGetStringi;
		extern gl_function<GLuint(GLuint, GLenum, GLchar *)> glGetSubroutineIndex;
		extern gl_function<GLint(GLuint, GLenum, GLchar *)> glGetSubroutineUniformLocation;
		extern gl_function<void(GLsync, GLenum, GLsizei, GLsizei *, GLint *)> glGetSynciv;
		extern gl_function<void(GLenum, GLint, GLenum, GLenum, GLvoid *)> glGetTexImage;
		extern gl_function<void(GLenum, GLint, GLenum, GLfloat *)> glGetTexLevelParameterfv;
		extern gl_function<void(GLenum, GLint, GLenum, GLint *)> glGetTexLevelParameteriv;
		extern gl_function<void(GLenum, GLenum, GLfloat *)> glGetTexParameterfv;
		extern gl_function<void(GLenum, GLenum, GLint *)> glGetTexParameteriv;
		extern gl_function<void(GLuint, GLuint, GLsizei, GLsizei *, GLsizei, GLenum *, char *)> glGetTransformFeedbackVarying;
		extern gl_function<void(GLuint, GLint, GLfloat *)> glGetUniformfv;
		extern gl_function<void(GLuint, GLint, GLint *)> glGetUniformiv;
		extern gl_function<GLuint(GLuint, GLchar *)> glGetUniformBlockIndex;
		extern gl_function<GLuint(GLuint, GLsizei, GLchar **, GLuint *)> glGetUniformIndices;
		extern gl_function<GLint(GLuint, const GLchar *)> glGetUniformLocation;
		extern gl_function<void(GLenum, GLint, GLuint *)> glGetUniformSubroutineuiv;
		extern gl_function<void(GLuint, GLenum, GLdouble *)> glGetVertexAttribdv;
		extern gl_function<void(GLuint, GLenum, GLfloat *)> glGetVertexAttribfv;
		extern gl_function<void(GLuint, GLenum, GLint *)> glGetVertexAttribiv;
		extern gl_function<void(GLuint, GLenum, GLint *)> glGetVertexAttribIiv;
		extern gl_function<void(GLuint, GLenum, GLuint *)> glGetVertexAttribIuiv;
		extern gl_function<void(GLuint, GLenum, GLdouble *)> glGetVertexAttribLdv;
		extern gl_function<void(GLuint, GLenum, GLvoid **)> glGetVertexAttribPointerv;
		extern gl_function<void(GLenum, GLenum)> glHint;
		extern gl_function<GLboolean(GLuint)> glIsBuffer;
		extern gl_function<GLboolean(GLenum)> glIsEnabled;
		extern gl_function<GLboolean(GLuint)> glIsFramebuffer;
		extern gl_function<GLboolean(GLuint)> glIsProgram;
		extern gl_function<GLboolean(GLuint)> glIsProgramPipeline;
		extern gl_function<GLboolean(GLuint)> glIsQuery;
		extern gl_function<GLboolean(GLuint)> glIsRenderbuffer;
		extern gl_function<GLboolean(GLuint)> glIsSampler;
		extern gl_function<GLboolean(GLuint)> glIsShader;
		extern gl_function<GLboolean(GLsync)> glIsSync;
		extern gl_function<GLboolean(GLuint)> glIsTexture;
		extern gl_function<GLboolean(GLuint)> glIsTransformFeedback;
		extern gl_function<GLboolean(GLuint)> glIsVertexArray;
		extern gl_function<void(GLfloat)> glLineWidth;
		extern gl_function<void(GLuint)> glLinkProgram;
		extern gl_function<void(GLenum)> glLogicOp;
		extern gl_function<void *(GLenum, GLenum)> glMapBuffer;
		extern gl_function<GLboolean(GLenum)> glUnmapBuffer;
		extern gl_function<void *(GLenum, GLintptr, GLsizeiptr, GLbitfield)> glMapBufferRange;
		extern gl_function<void(GLclampf)> glMinSampleShading;
		extern gl_function<void(GLenum, GLint *, GLsizei *, GLsizei)> glMultiDrawArrays;
		extern gl_function<void(GLenum, GLsizei *, GLenum, GLvoid **, GLsizei)> glMultiDrawElements;
		extern gl_function<void(GLenum, GLsizei *, GLenum, GLvoid **, GLsizei, GLint *)> glMultiDrawElementsBaseVertex;
		extern gl_function<void(GLenum, GLint)> glPatchParameteri;
		extern gl_function<void(GLenum, GLfloat *)> glPatchParameterfv;
		extern gl_function<void()> glPauseTransformFeedback;
		extern gl_function<void(GLenum, GLfloat)> glPixelStoref;
		extern gl_function<void(GLenum, GLint)> glPixelStorei;
		extern gl_function<void(GLenum, GLfloat)> glPointParameterf;
		extern gl_function<void(GLenum, GLint)> glPointParameteri;
		extern gl_function<void(GLenum, GLfloat *)> glPointParameterfv;
		extern gl_function<void(GLenum, GLint *)> glPointParameteriv;
		extern gl_function<void(GLfloat)> glPointSize;
		extern gl_function<void(GLenum, GLenum)> glPolygonMode;
		extern gl_function<void(GLfloat, GLfloat)> glPolygonOffset;
		extern gl_function<void(GLuint)> glPrimitiveRestartIndex;
		extern gl_function<void(GLuint, GLenum, void *, GLsizei)> glProgramBinary;
		extern gl_function<void(GLuint, GLenum, GLint)> glProgramParameteri;
		extern gl_function<void(GLuint, GLint, GLfloat)> glProgramUniform1f;
		extern gl_function<void(GLuint, GLint, GLfloat, GLfloat)> glProgramUniform2f;
		extern gl_function<void(GLuint, GLint, GLfloat, GLfloat, GLfloat)> glProgramUniform3f;
		extern gl_function<void(GLuint, GLint, GLfloat, GLfloat, GLfloat, GLfloat)> glProgramUniform4f;
		extern gl_function<void(GLuint, GLint, GLint)> glProgramUniform1i;
		extern gl_function<void(GLuint, GLint, GLint, GLint)> glProgramUniform2i;
		extern gl_function<void(GLuint, GLint, GLint, GLint, GLint)> glProgramUniform3i;
		extern gl_function<void(GLuint, GLint, GLint, GLint, GLint, GLint)> glProgramUniform4i;
		extern gl_function<void(GLuint, GLint, GLuint)> glProgramUniform1ui;
		extern gl_function<void(GLuint, GLint, GLint, GLuint)> glProgramUniform2ui;
		extern gl_function<void(GLuint, GLint, GLint, GLint, GLuint)> glProgramUniform3ui;
		extern gl_function<void(GLuint, GLint, GLint, GLint, GLint, GLuint)> glProgramUniform4ui;
		extern gl_function<void(GLuint, GLint, GLsizei, GLfloat *)> glProgramUniform1fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLfloat *)> glProgramUniform2fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLfloat *)> glProgramUniform3fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLfloat *)> glProgramUniform4fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLint *)> glProgramUniform1iv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLint *)> glProgramUniform2iv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLint *)> glProgramUniform3iv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLint *)> glProgramUniform4iv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLuint *)> glProgramUniform1uiv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLuint *)> glProgramUniform2uiv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLuint *)> glProgramUniform3uiv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLuint *)> glProgramUniform4uiv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLboolean, GLfloat *)> glProgramUniformMatrix2fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLboolean, GLfloat *)> glProgramUniformMatrix3fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLboolean, GLfloat *)> glProgramUniformMatrix4fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLboolean, GLfloat *)> glProgramUniformMatrix2x3fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLboolean, GLfloat *)> glProgramUniformMatrix3x2fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLboolean, GLfloat *)> glProgramUniformMatrix2x4fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLboolean, GLfloat *)> glProgramUniformMatrix4x2fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLboolean, GLfloat *)> glProgramUniformMatrix3x4fv;
		extern gl_function<void(GLuint, GLint, GLsizei, GLboolean, GLfloat *)> glProgramUniformMatrix4x3fv;
		extern gl_function<void(GLenum)> glProvokingVertex;
		extern gl_function<void(GLuint, GLenum)> glQueryCounter;
		extern gl_function<void(GLenum)> glReadBuffer;
		extern gl_function<void(GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *)> glReadPixels;
		extern gl_function<void()> glReleaseShaderCompiler;
		extern gl_function<void(GLenum, GLenum, GLsizei, GLsizei)> glRenderbufferStorage;
		extern gl_function<void(GLenum, GLsizei, GLenum, GLsizei, GLsizei)> glRenderbufferStorageMultisample;
		extern gl_function<void()> glResumeTransformFeedback;
		extern gl_function<void(GLclampf, GLboolean)> glSampleCoverage;
		extern gl_function<void(GLuint, GLbitfield)> glSampleMaski;
		extern gl_function<void(GLuint, GLenum, GLfloat)> glSamplerParameterf;
		extern gl_function<void(GLuint, GLenum, GLint)> glSamplerParameteri;
		extern gl_function<void(GLuint, GLenum, GLfloat *)> glSamplerParameterfv;
		extern gl_function<void(GLuint, GLenum, GLint *)> glSamplerParameteriv;
		extern gl_function<void(GLint, GLint, GLsizei, GLsizei)> glScissor;
		extern gl_function<void(GLuint, GLsizei, GLint *)> glScissorArrayv;
		extern gl_function<void(GLuint, GLint, GLint, GLsizei, GLsizei)> glScissorIndexed;
		extern gl_function<void(GLuint, GLint *)> glScissorIndexedv;
		extern gl_function<void(GLsizei, GLuint *, GLenum, void *, GLsizei)> glShaderBinary;
		extern gl_function<void(GLuint, GLsizei, const GLchar **, GLint *)> glShaderSource;
		extern gl_function<void(GLenum, GLint, GLuint)> glStencilFunc;
		extern gl_function<void(GLenum, GLenum, GLint, GLuint)> glStencilFuncSeparate;
		extern gl_function<void(GLuint)> glStencilMask;
		extern gl_function<void(GLenum, GLuint)> glStencilMaskSeparate;
		extern gl_function<void(GLenum, GLenum, GLenum)> glStencilOp;
		extern gl_function<void(GLenum, GLenum, GLenum, GLenum)> glStencilOpSeparate;
		extern gl_function<void(GLenum, GLenum, GLuint)> glTexBuffer;
		extern gl_function<void(GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, GLvoid *)> glTexImage1D;
		extern gl_function<void(GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid *)> glTexImage2D;
		extern gl_function<void(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLboolean)> glTexImage2DMultisample;
		extern gl_function<void(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid *)> glTexImage3D;
		extern gl_function<void(GLenum, GLsizei, GLint, GLsizei, GLsizei, GLsizei, GLboolean)> glTexImage3DMultisample;
		extern gl_function<void(GLenum, GLenum, GLfloat)> glTexParameterf;
		extern gl_function<void(GLenum, GLenum, GLint)> glTexParameteri;
		extern gl_function<void(GLenum, GLenum, GLfloat *)> glTexParameterfv;
		extern gl_function<void(GLenum, GLenum, GLint *)> glTexParameteriv;
		extern gl_function<void(GLenum, GLenum, GLint *)> glTexParameterIiv;
		extern gl_function<void(GLenum, GLenum, GLuint *)> glTexParameterIuiv;
		extern gl_function<void(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, GLvoid *)> glTexSubImage1D;
		extern gl_function<void(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *)> glTexSubImage2D;
		extern gl_function<void(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, GLvoid *)> glTexSubImage3D;
		extern gl_function<void(GLuint, GLsizei, char **, GLenum)> glTransformFeedbackVaryings;
		extern gl_function<void(GLint, GLfloat)> glUniform1f;
		extern gl_function<void(GLint, GLfloat, GLfloat)> glUniform2f;
		extern gl_function<void(GLint, GLfloat, GLfloat, GLfloat)> glUniform3f;
		extern gl_function<void(GLint, GLfloat, GLfloat, GLfloat, GLfloat)> glUniform4f;
		extern gl_function<void(GLint, GLint)> glUniform1i;
		extern gl_function<void(GLint, GLint, GLint)> glUniform2i;
		extern gl_function<void(GLint, GLint, GLint, GLint)> glUniform3i;
		extern gl_function<void(GLint, GLint, GLint, GLint, GLint)> glUniform4i;
		extern gl_function<void(GLint, GLuint)> glUniform1ui;
		extern gl_function<void(GLint, GLint, GLuint)> glUniform2ui;
		extern gl_function<void(GLint, GLint, GLint, GLuint)> glUniform3ui;
		extern gl_function<void(GLint, GLint, GLint, GLint, GLuint)> glUniform4ui;
		extern gl_function<void(GLint, GLsizei, const GLfloat *)> glUniform1fv;
		extern gl_function<void(GLint, GLsizei, const GLfloat *)> glUniform2fv;
		extern gl_function<void(GLint, GLsizei, const GLfloat *)> glUniform3fv;
		extern gl_function<void(GLint, GLsizei, const GLfloat *)> glUniform4fv;
		extern gl_function<void(GLint, GLsizei, const GLint *)> glUniform1iv;
		extern gl_function<void(GLint, GLsizei, const GLint *)> glUniform2iv;
		extern gl_function<void(GLint, GLsizei, const GLint *)> glUniform3iv;
		extern gl_function<void(GLint, GLsizei, const GLint *)> glUniform4iv;
		extern gl_function<void(GLint, GLsizei, const GLuint *)> glUniform1uiv;
		extern gl_function<void(GLint, GLsizei, const GLuint *)> glUniform2uiv;
		extern gl_function<void(GLint, GLsizei, const GLuint *)> glUniform3uiv;
		extern gl_function<void(GLint, GLsizei, const GLuint *)> glUniform4uiv;
		extern gl_function<void(GLint, GLsizei, GLboolean, const GLfloat *)> glUniformMatrix2fv;
		extern gl_function<void(GLint, GLsizei, GLboolean, const GLfloat *)> glUniformMatrix3fv;
		extern gl_function<void(GLint, GLsizei, GLboolean, const GLfloat *)> glUniformMatrix4fv;
		extern gl_function<void(GLint, GLsizei, GLboolean, const GLfloat *)> glUniformMatrix2x3fv;
		extern gl_function<void(GLint, GLsizei, GLboolean, const GLfloat *)> glUniformMatrix3x2fv;
		extern gl_function<void(GLint, GLsizei, GLboolean, const GLfloat *)> glUniformMatrix2x4fv;
		extern gl_function<void(GLint, GLsizei, GLboolean, const GLfloat *)> glUniformMatrix4x2fv;
		extern gl_function<void(GLint, GLsizei, GLboolean, const GLfloat *)> glUniformMatrix3x4fv;
		extern gl_function<void(GLint, GLsizei, GLboolean, const GLfloat *)> glUniformMatrix4x3fv;
		extern gl_function<void(GLuint, GLuint, GLuint)> glUniformBlockBinding;
		extern gl_function<void(GLenum, GLsizei, GLuint *)> glUniformSubroutinesuiv;
		extern gl_function<void(GLuint)> glUseProgram;
		extern gl_function<void(GLuint, GLbitfield, GLuint)> glUseProgramStages;
		extern gl_function<void(GLuint)> glValidateProgram;
		extern gl_function<void(GLuint)> glValidateProgramPipeline;
		extern gl_function<void(GLuint, GLfloat)> glVertexAttrib1f;
		extern gl_function<void(GLuint, GLshort)> glVertexAttrib1s;
		extern gl_function<void(GLuint, GLdouble)> glVertexAttrib1d;
		extern gl_function<void(GLuint, GLint)> glVertexAttribI1i;
		extern gl_function<void(GLuint, GLuint)> glVertexAttribI1ui;
		extern gl_function<void(GLuint, GLfloat, GLfloat)> glVertexAttrib2f;
		extern gl_function<void(GLuint, GLshort, GLshort)> glVertexAttrib2s;
		extern gl_function<void(GLuint, GLdouble, GLdouble)> glVertexAttrib2d;
		extern gl_function<void(GLuint, GLint, GLint)> glVertexAttribI2i;
		extern gl_function<void(GLuint, GLuint, GLuint)> glVertexAttribI2ui;
		extern gl_function<void(GLuint, GLfloat, GLfloat, GLfloat)> glVertexAttrib3f;
		extern gl_function<void(GLuint, GLshort, GLshort, GLshort)> glVertexAttrib3s;
		extern gl_function<void(GLuint, GLdouble, GLdouble, GLdouble)> glVertexAttrib3d;
		extern gl_function<void(GLuint, GLint, GLint, GLint)> glVertexAttribI3i;
		extern gl_function<void(GLuint, GLuint, GLuint, GLuint)> glVertexAttribI3ui;
		extern gl_function<void(GLuint, GLfloat, GLfloat, GLfloat, GLfloat)> glVertexAttrib4f;
		extern gl_function<void(GLuint, GLshort, GLshort, GLshort, GLshort)> glVertexAttrib4s;
		extern gl_function<void(GLuint, GLdouble, GLdouble, GLdouble, GLdouble)> glVertexAttrib4d;
		extern gl_function<void(GLuint, GLubyte, GLubyte, GLubyte, GLubyte)> glVertexAttrib4Nub;
		extern gl_function<void(GLuint, GLint, GLint, GLint, GLint)> glVertexAttribI4i;
		extern gl_function<void(GLuint, GLuint, GLuint, GLuint, GLuint)> glVertexAttribI4ui;
		extern gl_function<void(GLuint, GLdouble)> glVertexAttribL1d;
		extern gl_function<void(GLuint, GLdouble, GLdouble)> glVertexAttribL2d;
		extern gl_function<void(GLuint, GLdouble, GLdouble, GLdouble)> glVertexAttribL3d;
		extern gl_function<void(GLuint, GLdouble, GLdouble, GLdouble, GLdouble)> glVertexAttribL4d;
		extern gl_function<void(GLuint, GLfloat *)> glVertexAttrib1fv;
		extern gl_function<void(GLuint, GLshort *)> glVertexAttrib1sv;
		extern gl_function<void(GLuint, GLdouble *)> glVertexAttrib1dv;
		extern gl_function<void(GLuint, GLint *)> glVertexAttribI1iv;
		extern gl_function<void(GLuint, GLuint *)> glVertexAttribI1uiv;
		extern gl_function<void(GLuint, GLfloat *)> glVertexAttrib2fv;
		extern gl_function<void(GLuint, GLshort *)> glVertexAttrib2sv;
		extern gl_function<void(GLuint, GLdouble *)> glVertexAttrib2dv;
		extern gl_function<void(GLuint, GLint *)> glVertexAttribI2iv;
		extern gl_function<void(GLuint, GLuint *)> glVertexAttribI2uiv;
		extern gl_function<void(GLuint, GLfloat *)> glVertexAttrib3fv;
		extern gl_function<void(GLuint, GLshort *)> glVertexAttrib3sv;
		extern gl_function<void(GLuint, GLdouble *)> glVertexAttrib3dv;
		extern gl_function<void(GLuint, GLint *)> glVertexAttribI3iv;
		extern gl_function<void(GLuint, GLuint *)> glVertexAttribI3uiv;
		extern gl_function<void(GLuint, GLfloat *)> glVertexAttrib4fv;
		extern gl_function<void(GLuint, GLshort *)> glVertexAttrib4sv;
		extern gl_function<void(GLuint, GLdouble *)> glVertexAttrib4dv;
		extern gl_function<void(GLuint, GLint *)> glVertexAttrib4iv;
		extern gl_function<void(GLuint, GLbyte *)> glVertexAttrib4bv;
		extern gl_function<void(GLuint, GLubyte *)> glVertexAttrib4ubv;
		extern gl_function<void(GLuint, GLushort *)> glVertexAttrib4usv;
		extern gl_function<void(GLuint, GLuint *)> glVertexAttrib4uiv;
		extern gl_function<void(GLuint, GLbyte *)> glVertexAttrib4Nbv;
		extern gl_function<void(GLuint, GLshort *)> glVertexAttrib4Nsv;
		extern gl_function<void(GLuint, GLint *)> glVertexAttrib4Niv;
		extern gl_function<void(GLuint, GLubyte *)> glVertexAttrib4Nubv;
		extern gl_function<void(GLuint, GLushort *)> glVertexAttrib4Nusv;
		extern gl_function<void(GLuint, GLuint *)> glVertexAttrib4Nuiv;
		extern gl_function<void(GLuint, GLbyte *)> glVertexAttribI4bv;
		extern gl_function<void(GLuint, GLubyte *)> glVertexAttribI4ubv;
		extern gl_function<void(GLuint, GLshort *)> glVertexAttribI4sv;
		extern gl_function<void(GLuint, GLushort *)> glVertexAttribI4usv;
		extern gl_function<void(GLuint, GLint *)> glVertexAttribI4iv;
		extern gl_function<void(GLuint, GLuint *)> glVertexAttribI4uiv;
		extern gl_function<void(GLuint, GLdouble *)> glVertexAttribL1dv;
		extern gl_function<void(GLuint, GLdouble *)> glVertexAttribL2dv;
		extern gl_function<void(GLuint, GLdouble *)> glVertexAttribL3dv;
		extern gl_function<void(GLuint, GLdouble *)> glVertexAttribL4dv;
		extern gl_function<void(GLuint, GLenum, GLboolean, GLuint)> glVertexAttribP1ui;
		extern gl_function<void(GLuint, GLenum, GLboolean, GLuint)> glVertexAttribP2ui;
		extern gl_function<void(GLuint, GLenum, GLboolean, GLuint)> glVertexAttribP3ui;
		extern gl_function<void(GLuint, GLenum, GLboolean, GLuint)> glVertexAttribP4ui;
		extern gl_function<void(GLuint, GLuint)> glVertexAttribDivisor;
		extern gl_function<void(GLuint, GLint, GLenum, GLboolean, GLsizei, GLvoid *)> glVertexAttribPointer;
		extern gl_function<void(GLuint, GLint, GLenum, GLsizei, GLvoid *)> glVertexAttribIPointer;
		extern gl_function<void(GLuint, GLint, GLenum, GLsizei, GLvoid *)> glVertexAttribLPointer;
		extern gl_function<void(GLint, GLint, GLsizei, GLsizei)> glViewport;
		extern gl_function<void(GLuint, GLsizei, GLfloat *)> glViewportArrayv;
		extern gl_function<void(GLuint, GLfloat, GLfloat, GLfloat, GLfloat)> glViewportIndexedf;
		extern gl_function<void(GLuint, GLfloat *)> glViewportIndexedfv;
		extern gl_function<void(GLsync, GLbitfield, GLuint64)> glWaitSync;
	}
}

#endif // GAPI_FUNCTIONS_HPP
